/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author trant
 */
public class ItemSanPham extends javax.swing.JPanel {

    private String id;
    private String ma;
    private Integer trangThai;
    private ImageIcon defaultAvatar;

    public ItemSanPham() {
        initComponents();
        defaultAvatar = new ImageIcon(getClass().getClassLoader().getResource("icon/coffee.gif"));
        lblAvatarSp.setIcon(defaultAvatar);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMa() {
        return ma;
    }

    public void setMa(String ma) {
        this.ma = ma;
    }

    public Integer getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }

    public ImageIcon getDefaultAvatar() {
        return defaultAvatar;
    }

    public void setDefaultAvatar(ImageIcon defaultAvatar) {
        this.defaultAvatar = defaultAvatar;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return pnlDetail;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.pnlDetail = jPanel1;
    }

    public JLabel getLblAvatarSp() {
        return lblAvatarSp;
    }

    public void setLblAvatarSp(JLabel lblAvatarSp) {
        this.lblAvatarSp = lblAvatarSp;
    }

    public JLabel getLblGiaSp() {
        return lblGiaSp;
    }

    public void setLblGiaSp(JLabel lblGiaSp) {
        this.lblGiaSp = lblGiaSp;
    }

    public JLabel getLblSaleSp() {
        return lblSaleSp;
    }

    public void setLblSaleSp(JLabel lblSaleSp) {
        this.lblSaleSp = lblSaleSp;
    }

    public JLabel getLblTenKhuyenMai() {
        return lblTenKhuyenMai;
    }

    public void setLblTenKhuyenMai(JLabel lblTenKhuyenMai) {
        this.lblTenKhuyenMai = lblTenKhuyenMai;
    }

    public JLabel getLblTenSp() {
        return lblTenSp;
    }

    public void setLblTenSp(JLabel lblTenSp) {
        this.lblTenSp = lblTenSp;
    }

    public JPanel getPnlAvatar() {
        return pnlAvatar;
    }

    public void setPnlAvatar(JPanel pnlAvatar) {
        this.pnlAvatar = pnlAvatar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDetail = new javax.swing.JPanel();
        lblGiaSp = new javax.swing.JLabel();
        lblTenSp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTenKhuyenMai = new javax.swing.JLabel();
        pnlAvatar = new javax.swing.JPanel();
        lblSaleSp = new javax.swing.JLabel();
        lblAvatarSp = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(170, 216));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDetail.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetail.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGiaSp.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblGiaSp.setForeground(new java.awt.Color(255, 51, 51));
        lblGiaSp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGiaSp.setText("50000");
        pnlDetail.add(lblGiaSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 120, 18));

        lblTenSp.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        lblTenSp.setForeground(new java.awt.Color(204, 0, 0));
        lblTenSp.setText("Ca cao");
        pnlDetail.add(lblTenSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 150, 18));

        jLabel1.setText("VND");
        pnlDetail.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        add(pnlDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 70));

        lblTenKhuyenMai.setBackground(new java.awt.Color(255, 255, 255));
        lblTenKhuyenMai.setForeground(new java.awt.Color(255, 51, 51));
        lblTenKhuyenMai.setOpaque(true);
        add(lblTenKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 180, 30));

        pnlAvatar.setBackground(new java.awt.Color(255, 255, 255));
        pnlAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlAvatar.setLayout(new javax.swing.OverlayLayout(pnlAvatar));

        lblSaleSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sale_60px.png"))); // NOI18N
        pnlAvatar.add(lblSaleSp);

        lblAvatarSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvatarSp.setMaximumSize(new java.awt.Dimension(200, 300));
        lblAvatarSp.setMinimumSize(new java.awt.Dimension(200, 300));
        lblAvatarSp.setPreferredSize(new java.awt.Dimension(200, 330));
        lblAvatarSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAvatarSpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAvatarSpMouseExited(evt);
            }
        });
        pnlAvatar.add(lblAvatarSp);

        add(pnlAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void lblAvatarSpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarSpMouseEntered
        Color color = new Color(0, 153, 153);
        pnlDetail.setBackground(color);
    }//GEN-LAST:event_lblAvatarSpMouseEntered

    private void lblAvatarSpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarSpMouseExited
        pnlDetail.setBackground(Color.WHITE);
    }//GEN-LAST:event_lblAvatarSpMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvatarSp;
    private javax.swing.JLabel lblGiaSp;
    private javax.swing.JLabel lblSaleSp;
    private javax.swing.JLabel lblTenKhuyenMai;
    private javax.swing.JLabel lblTenSp;
    private javax.swing.JPanel pnlAvatar;
    private javax.swing.JPanel pnlDetail;
    // End of variables declaration//GEN-END:variables
}
