/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author trant
 */
public class ItemBan extends javax.swing.JPanel {

    /**
     * Creates new form itemBan
     */
    private boolean confirm = false;
    private Integer trangThai;//0:Empty-1:Full

    public ItemBan() {
        initComponents();
    }

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    public JLabel getLblAvatar() {
        return lblAvatar;
    }

    public void setLblAvatar(JLabel lblAvatar) {
        this.lblAvatar = lblAvatar;
    }

    public JLabel getLblSoBan() {
        return lblSoBan;
    }

    public void setLblSoBan(JLabel lblSoBan) {
        this.lblSoBan = lblSoBan;
    }

    public Integer getTrangThai() {
        return trangThai;
    }

    public void setTrangThai(Integer trangThai) {
        this.trangThai = trangThai;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSoBan = new javax.swing.JLabel();
        pnlAvatar = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblSoBan.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        lblSoBan.setForeground(new java.awt.Color(255, 0, 204));
        lblSoBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoBan.setText("10");
        lblSoBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        lblSoBan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSoBan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSoBan.setOpaque(true);
        lblSoBan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSoBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSoBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSoBanMouseExited(evt);
            }
        });

        pnlAvatar.setLayout(new javax.swing.OverlayLayout(pnlAvatar));

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/round_table_48px.png"))); // NOI18N
        lblAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        lblAvatar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAvatar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAvatar.setOpaque(true);
        lblAvatar.setPreferredSize(new java.awt.Dimension(60, 48));
        lblAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAvatarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAvatarMouseExited(evt);
            }
        });
        pnlAvatar.add(lblAvatar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblSoBan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblSoBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoBanMouseEntered
        if (trangThai == 0) {
            ColorEntered();
        }

    }//GEN-LAST:event_lblSoBanMouseEntered

    private void lblSoBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoBanMouseExited
        if (trangThai == 0) {
            ColorExited();
        }

    }//GEN-LAST:event_lblSoBanMouseExited

    private void lblAvatarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarMouseEntered
        if (trangThai == 0) {
            ColorEntered();
        }
    }//GEN-LAST:event_lblAvatarMouseEntered

    private void lblAvatarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAvatarMouseExited
        if (trangThai == 0) {
            ColorExited();
        }
    }//GEN-LAST:event_lblAvatarMouseExited

    public void changeStateConfirm() {
        if (confirm == true) {
            confirm = false;
        } else {
            confirm = true;
        }
    }

    private void ColorEntered() {
        Color color = new Color(0, 153, 102);
        lblAvatar.setBackground(color);
        lblSoBan.setBackground(color);
    }

    private void ColorExited() {
        Color color = new Color(214, 217, 223);
        lblAvatar.setBackground(color);
        lblSoBan.setBackground(color);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblSoBan;
    private javax.swing.JPanel pnlAvatar;
    // End of variables declaration//GEN-END:variables
}
