/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainmodel.TaiKhoanAdmin;
import domainmodel.TaiKhoanNguoiDung;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import service.ITaiKhoanNguoiDungService;
import service.implement.TaiKhoanNguoiDungService;
import viewmodel.NhanVienViewModel_Van;
import viewmodel.TaiKhoanNguoiDungViewModel;

/**
 *
 * @author trant
 */
public class QLNguoiDung extends javax.swing.JPanel {

    private DefaultTableModel defaultTableModel;
    private DefaultComboBoxModel<NhanVienViewModel_Van> comboBoxNV;
    private ITaiKhoanNguoiDungService iTaiKhoanNguoiDungService;
    TaiKhoanNguoiDungViewModel tkView = new TaiKhoanNguoiDungViewModel();
    List<TaiKhoanNguoiDungViewModel> listTkView = new ArrayList<>();
    List<NhanVienViewModel_Van> listNvView = new ArrayList<>();

    /**
     * Creates new form QLNguoiDung
     */
    public QLNguoiDung(TaiKhoanAdmin admin, TaiKhoanNguoiDung nguoiDung) {
        initComponents();
        iTaiKhoanNguoiDungService = new TaiKhoanNguoiDungService();
        comboBoxNV = new DefaultComboBoxModel<>();
        // tblNguoiDung.setRowSelectionInterval(0, 0);
        load_TK(iTaiKhoanNguoiDungService.getAllTkNguoiDung());
        addCbNhanVien();

    }

    private void load_TK(List<TaiKhoanNguoiDungViewModel> list) {
        defaultTableModel = (DefaultTableModel) tblNguoiDung.getModel();
        defaultTableModel.setRowCount(0);
        for (TaiKhoanNguoiDungViewModel x : list) {
            defaultTableModel.addRow(x.getDataTK());
        }

    }

    private void addCbNhanVien() {
        listNvView = iTaiKhoanNguoiDungService.getAllNV();
        comboBoxNV = (DefaultComboBoxModel) (new DefaultComboBoxModel<>(listNvView.toArray()));
        cbNhanVien.setModel((DefaultComboBoxModel) comboBoxNV);
    }

    private void fillDataToFormND(int row) {
        txtTenTaiKhoan.setText(tblNguoiDung.getValueAt(row, 1).toString());
        pw.setText(tblNguoiDung.getValueAt(row, 2).toString());
        if (tblNguoiDung.getValueAt(row, 3).toString().equalsIgnoreCase("(chưa có thông tin)")) {
            cbNhanVien.setEnabled(false);
        } else {
            cbNhanVien.setEnabled(true);
            for (int i = 0; i < cbNhanVien.getItemCount(); i++) {
                if (tblNguoiDung.getValueAt(row, 3).toString().equals(comboBoxNV.getElementAt(i).getMaNhanVien())) {
                    cbNhanVien.setSelectedIndex(i);
                    break;
                }
            }
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbNhanVien = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguoiDung = new javax.swing.JTable();
        btnThemTK = new javax.swing.JButton();
        btnCapNhapTK = new javax.swing.JButton();
        pw = new javax.swing.JPasswordField();
        txtTenTaiKhoan = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblHienThi = new javax.swing.JLabel();
        rdoDangHD = new javax.swing.JRadioButton();
        rdoDungHD = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(108, 83, 54));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(225, 218, 197));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên Tài Khoản");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(225, 218, 197));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mật Khẩu");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(225, 218, 197));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nhân Viên");

        cbNhanVien.setBackground(new java.awt.Color(225, 218, 197));
        cbNhanVien.setForeground(new java.awt.Color(108, 83, 54));
        cbNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNhanVienItemStateChanged(evt);
            }
        });
        cbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNhanVienActionPerformed(evt);
            }
        });

        tblNguoiDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Tên Tài Khoản", "Mật Khẩu", "Mã Nhân Viên", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNguoiDung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguoiDungMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguoiDung);
        if (tblNguoiDung.getColumnModel().getColumnCount() > 0) {
            tblNguoiDung.getColumnModel().getColumn(0).setMinWidth(0);
            tblNguoiDung.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        btnThemTK.setBackground(new java.awt.Color(225, 218, 197));
        btnThemTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemTK.setForeground(new java.awt.Color(108, 83, 54));
        btnThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add_20px.png"))); // NOI18N
        btnThemTK.setText("Thêm");
        btnThemTK.setBorderPainted(false);
        btnThemTK.setFocusPainted(false);
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        btnCapNhapTK.setBackground(new java.awt.Color(225, 218, 197));
        btnCapNhapTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhapTK.setForeground(new java.awt.Color(108, 83, 54));
        btnCapNhapTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_sync_30px.png"))); // NOI18N
        btnCapNhapTK.setText("Cập Nhật");
        btnCapNhapTK.setBorderPainted(false);
        btnCapNhapTK.setFocusPainted(false);
        btnCapNhapTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapTKActionPerformed(evt);
            }
        });

        pw.setBackground(new java.awt.Color(225, 218, 197));

        txtTenTaiKhoan.setBackground(new java.awt.Color(225, 218, 197));

        btnXoa.setBackground(new java.awt.Color(225, 218, 197));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(108, 83, 54));
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_remove_30px.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setFocusPainted(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(225, 218, 197));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(108, 83, 54));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.setBorderPainted(false);
        btnLamMoi.setFocusPainted(false);
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lblHienThi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHienThi.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(rdoDangHD);
        rdoDangHD.setText("Đang hoạt động");
        rdoDangHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDangHDActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoDungHD);
        rdoDungHD.setText("Dừng hoạt động");
        rdoDungHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDungHDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhapTK)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(pw, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(txtTenTaiKhoan)
                        .addComponent(cbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHienThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdoDangHD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(rdoDungHD)
                        .addGap(57, 57, 57))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoDangHD)
                    .addComponent(rdoDungHD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(lblHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCapNhapTK)
                                .addComponent(btnXoa))
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNhanVienActionPerformed

    }//GEN-LAST:event_cbNhanVienActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
        NhanVienViewModel_Van nvView1 = new NhanVienViewModel_Van();
        if (checkFormEmpty(txtTenTaiKhoan, pw) && checkTenTK(txtTenTaiKhoan.getText())
                && checkTaiKhoanCuaNhanVien(((NhanVienViewModel_Van) cbNhanVien.getSelectedItem()).getMaNhanVien())) {
            NhanVienViewModel_Van nvView = (NhanVienViewModel_Van) comboBoxNV.getSelectedItem();
            iTaiKhoanNguoiDungService.inserttkNguoiDung(txtTenTaiKhoan.getText(), pw.getText(), nvView);
            JOptionPane.showMessageDialog(this, "Thêm Tai Khoan thành công");
            load_TK(iTaiKhoanNguoiDungService.getAllTkNguoiDung());
        }
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnCapNhapTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapTKActionPerformed
        int row = tblNguoiDung.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Click on table,please");
        } else {
            if (tblNguoiDung.getValueAt(row, 3).toString().
                    equalsIgnoreCase(((NhanVienViewModel_Van) cbNhanVien.getSelectedItem()).getMaNhanVien())) {
                NhanVienViewModel_Van nvView = (NhanVienViewModel_Van) comboBoxNV.getSelectedItem();
                iTaiKhoanNguoiDungService.updateTKNguoiDung(tblNguoiDung.getValueAt(row, 0).toString(), txtTenTaiKhoan.getText(), pw.getText(), nvView);
                JOptionPane.showMessageDialog(this, "Update Success");
                load_TK(iTaiKhoanNguoiDungService.getAllTkNguoiDung());
                btnLamMoiActionPerformed(evt);
            } else {
                if (checkTaiKhoanCuaNhanVien(((NhanVienViewModel_Van) cbNhanVien.getSelectedItem()).getMaNhanVien())) {
                    NhanVienViewModel_Van nvView = (NhanVienViewModel_Van) comboBoxNV.getSelectedItem();
                    iTaiKhoanNguoiDungService.updateTKNguoiDung(tblNguoiDung.getValueAt(row, 0).toString(), txtTenTaiKhoan.getText(), pw.getText(), nvView);
                    JOptionPane.showMessageDialog(this, "Update Success");
                    load_TK(iTaiKhoanNguoiDungService.getAllTkNguoiDung());
                    btnLamMoiActionPerformed(evt);
                }
            }

        }
    }//GEN-LAST:event_btnCapNhapTKActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tblNguoiDung.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Click on table,please");
        } else {
            iTaiKhoanNguoiDungService.deletetkNguoiDung(tblNguoiDung.getValueAt(row, 0).toString());
            JOptionPane.showMessageDialog(this, "Delete Success");
            load_TK(iTaiKhoanNguoiDungService.getAllTkNguoiDung());
            btnLamMoiActionPerformed(evt);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblNguoiDungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguoiDungMouseClicked
        int row = tblNguoiDung.getSelectedRow();
        fillDataToFormND(row);
    }//GEN-LAST:event_tblNguoiDungMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        cbNhanVien.setSelectedIndex(0);
        txtTenTaiKhoan.setText("");
        pw.setText("");
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void cbNhanVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNhanVienItemStateChanged
        for (NhanVienViewModel_Van nvView : iTaiKhoanNguoiDungService.getAllNV()) {
            if (nvView.getMaNhanVien().equals(comboBoxNV.getSelectedItem().toString())) {
                lblHienThi.setText(nvView.getHoTen());
                break;
            }

        }
    }//GEN-LAST:event_cbNhanVienItemStateChanged

    private void rdoDangHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDangHDActionPerformed
       defaultTableModel = (DefaultTableModel) tblNguoiDung.getModel();
        defaultTableModel.setRowCount(0);
        for (TaiKhoanNguoiDungViewModel x : iTaiKhoanNguoiDungService.getAllTkNguoiDung()) {
            if (x.getTrangthai()== 1) {
                defaultTableModel.addRow(new Object[]{x.getDataTK()});
            }

        }

    }//GEN-LAST:event_rdoDangHDActionPerformed

    private void rdoDungHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDungHDActionPerformed
        defaultTableModel = (DefaultTableModel) tblNguoiDung.getModel();
        defaultTableModel.setRowCount(0);
        for (TaiKhoanNguoiDungViewModel x : iTaiKhoanNguoiDungService.getAllTkNguoiDung()) {
            if (x.getTrangthai()== 0) {
                defaultTableModel.addRow(new Object[]{x.getDataTK()});
            }

        }

    }//GEN-LAST:event_rdoDungHDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhapTK;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbNhanVien;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHienThi;
    private javax.swing.JPasswordField pw;
    private javax.swing.JRadioButton rdoDangHD;
    private javax.swing.JRadioButton rdoDungHD;
    private javax.swing.JTable tblNguoiDung;
    private javax.swing.JTextField txtTenTaiKhoan;
    // End of variables declaration//GEN-END:variables
private boolean checkFormEmpty(JTextField tentkField, JPasswordField pw) {
        if (tentkField.getText().isBlank() || pw.getPassword().toString().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được trống");
            return false;
        } else {
            return true;
        }
    }

    private boolean checkMatcher(String Ma) {
        List<NhanVienViewModel_Van> list = new ArrayList<>();
        list = iTaiKhoanNguoiDungService.getAllNV();
        for (NhanVienViewModel_Van nv : list) {
            if (nv.equals(nv.getMaNhanVien())) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại");
                return false;
            }
        }
        return true;
    }

    private boolean checkTenTK(String Tentk) {
        List<TaiKhoanNguoiDungViewModel> list = new ArrayList<>();
        list = iTaiKhoanNguoiDungService.getAllTkNguoiDung();
        for (TaiKhoanNguoiDungViewModel tk : list) {
            if (Tentk.equals(tk.getTenTk())) {
                JOptionPane.showMessageDialog(this, "Tên tài khoản đã tồn tại");
                return false;
            }
        }
        return true;
    }

    private boolean checkTaiKhoanCuaNhanVien(String maNhanVien) {
        List<TaiKhoanNguoiDungViewModel> list = new ArrayList<>();
        list = iTaiKhoanNguoiDungService.getAllTkNguoiDung();
        for (TaiKhoanNguoiDungViewModel tk : list) {
            if (maNhanVien.equals(tk.getMaNhanVien())) {
                JOptionPane.showMessageDialog(this, "Nhân viên này đã có tài khoản");
                return false;
            }
        }
        return true;
    }
}
