/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Set;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.implement.ChiTietSpService;
import service.IChiTietSpService;
import service.ISanPhamService;
import service.implement.SanPhamService;
import viewmodel.ChiTietSPViewModel;
import viewmodel.NguyenLieuDangSuDung;
import viewmodel.SanPhamViewModel;

/**
 *
 * @author trant
 */
public class QLSanPham extends javax.swing.JPanel {

    /**
     * Creates new form QLSanPham
     */
    private DefaultTableModel modelTableSanPham;
    private DefaultTableModel modelTableDinhLuong;
    private ISanPhamService sanPhamService;
    private IChiTietSpService chiTietSPService;
    private DefaultComboBoxModel<NguyenLieuDangSuDung> modelComBoNguyenLieu;
    private byte[] _arrAvatar;
    private ImageIcon defaultAvatar;

    public QLSanPham() {
        initComponents();
        sanPhamService = new SanPhamService();
        chiTietSPService = new ChiTietSpService();
        modelTableSanPham = new DefaultTableModel();
        modelTableDinhLuong = new DefaultTableModel();
        modelComBoNguyenLieu = (DefaultComboBoxModel) new DefaultComboBoxModel<>(sanPhamService.getAllNguyenLieu().toArray());
        cboNguyenLieu.setModel((DefaultComboBoxModel) modelComBoNguyenLieu);
        Image image = new ImageIcon(getClass().getClassLoader().getResource("icon\\add-image.png")).getImage();
        defaultAvatar = new ImageIcon(image.getScaledInstance(187, 186, Image.SCALE_SMOOTH));
        lblAnh.setIcon(defaultAvatar);
        ShowSanPhamToTable(sanPhamService.getAllSanPham());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaSp = new javax.swing.JTextField();
        txtTenSp = new javax.swing.JTextField();
        txtGiaBan = new javax.swing.JTextField();
        lblAnh = new javax.swing.JLabel();
        lbUpload = new javax.swing.JLabel();
        btnThemSP = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDinhLuong = new javax.swing.JTable();
        cboNguyenLieu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        pnlLeft.setBackground(new java.awt.Color(225, 218, 197));
        pnlLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thêm sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(108, 83, 54))); // NOI18N
        pnlLeft.setForeground(new java.awt.Color(108, 83, 54));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 83, 54));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Mã Sản Phẩm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 83, 54));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tên Sản Phẩm");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(108, 83, 54));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Giá bán");

        txtMaSp.setBackground(new java.awt.Color(225, 218, 197));
        txtMaSp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        txtTenSp.setBackground(new java.awt.Color(225, 218, 197));
        txtTenSp.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        txtGiaBan.setBackground(new java.awt.Color(225, 218, 197));
        txtGiaBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        lblAnh.setOpaque(true);

        lbUpload.setBackground(new java.awt.Color(255, 153, 153));
        lbUpload.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbUpload.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUpload.setText("Upload");
        lbUpload.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbUpload.setOpaque(true);
        lbUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUploadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbUploadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbUploadMouseExited(evt);
            }
        });

        btnThemSP.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnThemSP.setText("Thêm sản phẩm");
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Bảng định lượng nguyên liệu"));

        tblDinhLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Mã nguyên liệu", "Tên nguyên liệu", "Định lượng(gam)", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDinhLuong.getTableHeader().setReorderingAllowed(false);
        tblDinhLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDinhLuongMouseClicked(evt);
            }
        });
        tblDinhLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblDinhLuongKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tblDinhLuong);
        if (tblDinhLuong.getColumnModel().getColumnCount() > 0) {
            tblDinhLuong.getColumnModel().getColumn(0).setMinWidth(0);
            tblDinhLuong.getColumnModel().getColumn(0).setMaxWidth(0);
            tblDinhLuong.getColumnModel().getColumn(1).setResizable(false);
            tblDinhLuong.getColumnModel().getColumn(2).setResizable(false);
            tblDinhLuong.getColumnModel().getColumn(3).setResizable(false);
            tblDinhLuong.getColumnModel().getColumn(4).setMinWidth(35);
            tblDinhLuong.getColumnModel().getColumn(4).setMaxWidth(35);
        }

        cboNguyenLieu.setBorder(null);
        cboNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNguyenLieuActionPerformed(evt);
            }
        });

        jLabel5.setText("Chọn nguyên liệu");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlLeftLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(txtGiaBan, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addGroup(pnlLeftLayout.createSequentialGroup()
                                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenSp)
                                    .addComponent(txtMaSp))))
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLeftLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74))
                            .addGroup(pnlLeftLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(btnThemSP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLeftLayout.createSequentialGroup()
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenSp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pnlRight.setBackground(new java.awt.Color(225, 218, 197));
        pnlRight.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(108, 83, 54))); // NOI18N
        pnlRight.setForeground(new java.awt.Color(108, 83, 54));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Mã", "Tên sản phẩm", "Giá bán"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.getTableHeader().setReorderingAllowed(false);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSanPham);
        if (tblSanPham.getColumnModel().getColumnCount() > 0) {
            tblSanPham.getColumnModel().getColumn(0).setMinWidth(0);
            tblSanPham.getColumnModel().getColumn(0).setMaxWidth(0);
            tblSanPham.getColumnModel().getColumn(1).setMinWidth(40);
            tblSanPham.getColumnModel().getColumn(1).setMaxWidth(40);
            tblSanPham.getColumnModel().getColumn(2).setResizable(false);
            tblSanPham.getColumnModel().getColumn(3).setResizable(false);
        }

        btnCapNhat.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlRightLayout = new javax.swing.GroupLayout(pnlRight);
        pnlRight.setLayout(pnlRightLayout);
        pnlRightLayout.setHorizontalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRightLayout.createSequentialGroup()
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                    .addGroup(pnlRightLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRightLayout.setVerticalGroup(
            pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ShowSanPhamToTable(List<SanPhamViewModel> list) {
        modelTableSanPham = (DefaultTableModel) tblSanPham.getModel();
        modelTableSanPham.setRowCount(0);
        for (SanPhamViewModel sp : list) {
            modelTableSanPham.addRow(new Object[]{sp.getIdSp(), sp.getMaSp(),
                sp.getTenSp(), sp.getGiaBan()});
        }
    }
    private void lbUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUploadMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        int choice = fileChooser.showOpenDialog(this);
        if (choice == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();//return file selected-gán path cho File
            Image image = new ImageIcon(file.getAbsolutePath()).getImage().getScaledInstance(187, 186, Image.SCALE_SMOOTH);
            lblAnh.setIcon(new ImageIcon(image));//tao đối tượng ImageIcon(lấy path file truyền vào)rồi seticon cho label
            try {
                BufferedImage bufferedImage = ImageIO.read(file);
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(bufferedImage, "png", baos);
                _arrAvatar = new byte[baos.toByteArray().length];
                _arrAvatar = baos.toByteArray();

            } catch (IOException ex) {

            }

        }

    }//GEN-LAST:event_lbUploadMouseClicked

    private void lbUploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUploadMouseEntered
        lbUpload.setBackground(Color.GREEN);
    }//GEN-LAST:event_lbUploadMouseEntered

    private void lbUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUploadMouseExited
        Color color = new Color(255, 153, 153);
        lbUpload.setBackground(color);
    }//GEN-LAST:event_lbUploadMouseExited

    private void showChiTietSanPham(String idSp) {
        modelTableDinhLuong = (DefaultTableModel) tblDinhLuong.getModel();
        modelTableDinhLuong.setRowCount(0);
        SanPhamViewModel spView = sanPhamService.getSanPhamById(idSp);
        Set<ChiTietSPViewModel> chiTietView = chiTietSPService.getChiTietSpByIdSanPham(idSp);
        for (ChiTietSPViewModel ctView : chiTietView) {
            modelTableDinhLuong.addRow(new Object[]{ctView.getIdNguyenLieu(), ctView.getMaNguyenLieu(),
                ctView.getTenNguyenLieu(), ctView.getDinhLuong()});
        }
        _arrAvatar = spView.getAvatar();
        if (spView.getAvatar() != null) {
            Image image = new ImageIcon(_arrAvatar).getImage().getScaledInstance(187, 186, Image.SCALE_SMOOTH);
            lblAnh.setIcon(new ImageIcon(image));
        } else {
            lblAnh.setIcon(defaultAvatar);
        }

    }

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        int row = tblSanPham.getSelectedRow();
        showChiTietSanPham(tblSanPham.getValueAt(row, 0).toString());

    }//GEN-LAST:event_tblSanPhamMouseClicked


    private void cboNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNguyenLieuActionPerformed
        int count = 0;
        if (cboNguyenLieu.getItemCount() <= 0) {
            JOptionPane.showMessageDialog(jPanel4, "Vui lòng bổ sung nguyên liệu");
        } else {
            modelTableDinhLuong = (DefaultTableModel) tblDinhLuong.getModel();
            NguyenLieuDangSuDung nguyenLieu = (NguyenLieuDangSuDung) modelComBoNguyenLieu.getSelectedItem();
            for (int i = 0; i < tblDinhLuong.getRowCount(); i++) {
                if (nguyenLieu.getId().equalsIgnoreCase(tblDinhLuong.getValueAt(i, 0).toString())) {
                    count++;
                    break;
                }
            }
            if (count == 0) {
                modelTableDinhLuong.addRow(new Object[]{nguyenLieu.getId(), nguyenLieu.getMa(), nguyenLieu.getTen(), 1});
            }
        }
    }//GEN-LAST:event_cboNguyenLieuActionPerformed

    public boolean checkNumber(String mark) {
        Pattern regexInt = Pattern.compile("^[0-9]+$");
        Pattern regexDouble = Pattern.compile("^[0-9]+(\\.)[0-9]+$");
        if (!regexInt.matcher(mark).find() && !regexDouble.matcher(mark).find()) {
            return false;
        } else {
            return true;
        }
    }

    private void tblDinhLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblDinhLuongKeyReleased
        int row = tblDinhLuong.getSelectedRow();
        String soLuong = tblDinhLuong.getValueAt(row, 3).toString();
        if (!checkNumber(soLuong)) {
            JOptionPane.showMessageDialog(jPanel4, "Số lượng không hợp lệ !");
            tblDinhLuong.setValueAt(1, row, 3);
        }
    }//GEN-LAST:event_tblDinhLuongKeyReleased

    private void tblDinhLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDinhLuongMouseClicked
        modelTableDinhLuong = (DefaultTableModel) tblDinhLuong.getModel();
        int row = tblDinhLuong.getSelectedRow();
        if (tblDinhLuong.getSelectedColumn() == 4) {
            if (tblDinhLuong.getValueAt(row, 4).equals(true)) {
                modelTableDinhLuong.removeRow(row);
            }
        }

    }//GEN-LAST:event_tblDinhLuongMouseClicked

    private boolean checkEmpty() {
        if (txtMaSp.getText().isBlank() || txtTenSp.getText().isBlank() || txtGiaBan.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
            return false;
        } else if (tblDinhLuong.getRowCount() <= 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng thêm định lượng");
            return false;
        }
        return true;
    }

    private boolean checkMaSp(String maSp) {
        if (sanPhamService.getSanPhamByMa(maSp) != null) {
            JOptionPane.showMessageDialog(pnlLeft, "Mã sản phẩm đã tồn tại");
            return true;
        } else {
            return false;
        }
    }

    private void clearForm() {
        modelTableDinhLuong = (DefaultTableModel) tblDinhLuong.getModel();
        modelTableDinhLuong.setRowCount(0);
        cboNguyenLieu.setSelectedIndex(0);
        lblAnh.setIcon(defaultAvatar);
        txtMaSp.setText("");
        txtTenSp.setText("");
        txtGiaBan.setText("");

    }
    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        if (checkEmpty() && checkNumber(txtGiaBan.getText()) && !checkMaSp(txtMaSp.getText())) {
            sanPhamService.insertSanPham(txtMaSp.getText(), txtTenSp.getText(), Float.parseFloat(txtGiaBan.getText()), _arrAvatar);
            for (int i = 0; i < tblDinhLuong.getRowCount(); i++) {
                chiTietSPService.insertChiTietSanPham(Float.parseFloat(tblDinhLuong.getValueAt(i, 3).toString()),
                        sanPhamService.getSanPhamByMa(txtMaSp.getText()).getIdSp(), tblDinhLuong.getValueAt(i, 0).toString());
            }
            ShowSanPhamToTable(sanPhamService.getAllSanPham());
            clearForm();
            JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công");
        }
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int row = tblSanPham.getSelectedRow();
        sanPhamService.UpdateSanPham(
                tblSanPham.getValueAt(row, 0).toString(),
                tblSanPham.getValueAt(row, 1).toString(),
                tblSanPham.getValueAt(row, 2).toString(),
                Float.parseFloat(tblSanPham.getValueAt(row, 3).toString()),
                _arrAvatar);
    }//GEN-LAST:event_btnCapNhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboNguyenLieu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbUpload;
    private javax.swing.JLabel lblAnh;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTable tblDinhLuong;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaSp;
    private javax.swing.JTextField txtTenSp;
    // End of variables declaration//GEN-END:variables
}
